### ISSUE TITLE
[Question] Suggestions for hyperparameter tuning? 

### ISSUE THREAD

**Issue by jolespin** [eliorc/node2vec#10]
Do you recommend any recommendation for tuning hyperparameters based on network topology? Specifically, I usually deal with fully connected correlation-style networks with 100 - 5000 nodes.  

**From your experimentation, what is your thought process when tuning these hyperparameters?** 

```
node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=200, workers=4) 

# Embed nodes
model = node2vec.fit(window=10, min_count=1, batch_words=4)
```

**Comment by eliorc** [comment]
Well, it really depends which kind of information you are looking to emphasize.
I usually define some kind of metric (for example, random index for clustering evaluation where the clusters are the different levels of affinity I expect to embed) and do some hyperparameter search looking while looking for the best metric result...

There is no one off solution I can give you, hope it helps
