### ISSUE TITLE
How can node2vec use GPU

### ISSUE THREAD

**Issue by coolabhishek** [eliorc/node2vec#100]
The code is slow in computing 

>>> node2vec = Node2Vec(G, dimensions=64, walk_length=30, num_walks=200, workers=4)
Computing transition probabilities:   0%|▏                                     | 93/19255 [1:01:27<130:24:08, 24.50s/it]

Computing transition probabilities:   1%|▏                                    | 127/19255 [1:22:21<201:05:13, 37.85s/it]

Is there a way to make the execution Faster? I have a GPU, is it possible to leverage?

**Comment by eliorc** [comment]
Unfortunately no, there is no support for that - it is also mentioned as a TODO in the README
