### ISSUE TITLE
failing simple clustering of synthetic networks

### ISSUE THREAD

**Issue by yuanmohe** [eliorc/node2vec#103]
Hi Elior,

I am trying to use the library to vectorise the nodes and then cluster, as in [Goyal and Ferrara (2018) Figure 4](https://www.sciencedirect.com/science/article/pii/S0950705118301540). But it seems the algorithm is not performing well even in very simple synthetic networks. 

For example, I created a synthetic network of 900 nodes with 3 communities. Used node2vec to vectorise the nodes, reduced the dimension to two with TSNE and visualised the nodes as the plot below. The colour represents true communities. If the algorithm works, the colour should perfectly align with the clusters, but it is quite mixed.

![github](https://github.com/eliorc/node2vec/assets/49315550/7fbda503-c241-47d4-94fd-304c811279e0)

Code as below:
```python
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from node2vec import Node2Vec

# create the synthetic network
sizes = [300, 300, 300]
probs = [[0.2, 0.01, 0.01], [0.01, 0.2, 0.01], [0.01, 0.01, 0.2]]
G = nx.stochastic_block_model(sizes, probs, seed=0)
node_colors =  [0] * 300 + [1] * 300 + [2] * 300

# train the model
m_node = Node2Vec(G, dimensions = 128, p = 1, q = 1, walk_length = 80, num_walks = 10).fit()

# get the vectors
vectors = {node: m_node.wv[node] for node in G.nodes()}
vectors = pd.DataFrame.from_dict(vectors, orient = 'index')

# prepare dataframe for visualisation
model = TSNE(n_components=2)
df = model.fit_transform(vectors)
df = pd.DataFrame(df, index = G.nodes())
df = df.rename(columns = {0: 'dim1', 1: 'dim2'})
df = df.assign(color = node_colors)

# plot
fig, ax = plt.subplots()
sns.scatterplot(data = df, x = 'dim1', y = 'dim2', hue = 'color', palette = 'Set1', alpha = 0.6)
ax.set_xlabel("dim1")
ax.set_ylabel("dim2")
```
I tried another implementation from [github](https://github.com/shenweichen/GraphEmbedding), and it works well, resulting in a plot as below.

![github2](https://github.com/eliorc/node2vec/assets/49315550/0a2ccbeb-b911-4b7d-86c2-cd3397aeaf17)

I am puzzled by this. Is something weird happening with your implementation, or am I missing something? Looking forward to your take on this.

**Comment by eliorc** [comment]
Very very strange indeed, can you attach the code you used for the other implementation? I want to figure out where things go wrong

**Comment by eliorc** [comment]
I can totally see why you are puzzled by this :)

It is written in the README, but apparently not clear enough 😅 - Output node names are ALWAYS string.
When you write `m_node.wv[0]` you actually get the vector in the first index, and it is not guaranteed (and most likely won't be) the vector that is marked as `0` in the networkx graph.

In the line `vectors = {node: m_node.wv[node] for node in G.nodes()}`, cast to string by switching it to `vectors = {node: m_node.wv[str(node)] for node in G.nodes()}` and it will work as expected

Here is the code with this small change and the result, hope this makes sense :)

```python
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from node2vec import Node2Vec

# create the synthetic network
sizes = [300, 300, 300]
probs = [[0.2, 0.01, 0.01], [0.01, 0.2, 0.01], [0.01, 0.01, 0.2]]
G = nx.stochastic_block_model(sizes, probs, seed=0)
node_colors =  [0] * 300 + [1] * 300 + [2] * 300

# train the model
m_node = Node2Vec(G, dimensions = 128, p = 1, q = 1, walk_length = 80, num_walks = 10).fit()

# get the vectors
vectors = {node: m_node.wv[str(node)] for node in G.nodes()}
vectors = pd.DataFrame.from_dict(vectors, orient = 'index')

# prepare dataframe for visualisation
model = TSNE(n_components=2)
df = model.fit_transform(vectors)
df = pd.DataFrame(df, index = G.nodes())
df = df.rename(columns = {0: 'dim1', 1: 'dim2'})
df = df.assign(color = node_colors)

# plot
fig, ax = plt.subplots()
sns.scatterplot(data = df, x = 'dim1', y = 'dim2', hue = 'color', palette = 'Set1', alpha = 0.6)
ax.set_xlabel("dim1")
ax.set_ylabel("dim2")
```

![image](https://github.com/eliorc/node2vec/assets/17727283/db6cde4c-a759-4893-bcbb-5ca7518a37ab)

**Comment by yuanmohe** [comment]
Oh, that's the reason. 😂 Thank you!
