### ISSUE TITLE
if i use weighted graphs,how to set "weight_key"?

### ISSUE THREAD

**Issue by neuronblack** [eliorc/node2vec#11]

**Comment by eliorc** [comment]
When using `networkx` if you set your weights in the standard way, the `networkx` library will already store the edges weight under a key named `weight` - In this case you don't need to do anything special, meaning the weights you have set are going to be used by default.

If for any reason, you stored your networks weight under another property, you can tell `node2vec` library where you stored it, on the `Node2Vec` constructor just pass the `weight_key=<your_custom_weight_key>` and it will be handled for you.

**Comment by neuronblack** [comment]
thanks
