### ISSUE TITLE
what's the difference with aditya-grover' node2vec implementation?

### ISSUE THREAD

**Issue by superPershing** [eliorc/node2vec#14]
I see aditya-grover have implemented <https://github.com/aditya-grover/node2vec> before and it support spark version. I find your node2vec later. Your implementation is also perfect, but why you reinvent the wheel?

**Comment by eliorc** [comment]
Aditya's implementation is in Python2 and meant to work as a script. 
This repository is implemented in Python3 available is a PyPI package, and can be called as a library by importing it - the algorithm is the same.

**Comment by superPershing** [comment]
Good!
