### ISSUE TITLE
How to use EDGES_EMBEDDING_FILENAME as an input for Neural Network

### ISSUE THREAD

**Issue by Hemnepal** [eliorc/node2vec#15]
I have 1000 of small graphs, I can create EDGES_EMBEDDING_FILENAME for all of them. How can I use them as an input in any of the Machine Learning algorithm (mainly NN)? Could you please provide  me some suggestions?

**Comment by eliorc** [comment]
the EDGES_EMBEDDING_FILENAME is just a string so you can write your embeddings to the file specified by it.
Once you've generated the embeddings you can use it in your algorithms like any other text embeddings - create an embedding matrix and in your input data represent each edge as an index in the embedding matrix, then just use lookup to draw the embeddings for each training instance.

Technical details can be found on any tutorial that uses text embeddings, just in your case the words are edges (possible nodes too) and the embedding matrix are the values you saved to EDGES_EMBEDDING_FILENAME
