### ISSUE TITLE
Documentation to load model and embeddings? 

### ISSUE THREAD

**Issue by villanuevab** [eliorc/node2vec#16]
Is there documentation showing how to load model and embeddings after saving using the methods shown in the README?

**Comment by eliorc** [comment]
Hey, `node2vec` essentially returns a `gensim.models.KeyedVectors` instance, that holds all of the embeddings - to load a model / embeddings you can follow the instructions on [this page](https://radimrehurek.com/gensim/models/word2vec.html)

Use the `.load` to load a trained model (not really what you will use most of the time) or `.load_word2vec_format` to load already-trained embeddings (this is what you will use most of the time)

Hope that helps

**Comment by analyticalpicasso** [comment]
Hi, Is there a possibility to load this model and embeddings using Node2Vec source code only? since we have licencing issues with Word2Vec

**Comment by eliorc** [comment]
This package uses gensim under the hood, if you can't use gensim as per license I would avoid using this library aswell
