### ISSUE TITLE
How to set the parameters of the cora dataset?

### ISSUE THREAD

**Issue by HaiQW** [eliorc/node2vec#18]
I've run node2vec on the cora dataset for many times. For each run, I used the different settings of the parameters of the node2vec. However, |'ve never achieved the same or the nearly same result of the paper 'Evaluating Network Embeddings: Node2Vec vs Spectral Clustering vs GCN'.

**Comment by eliorc** [comment]
Which results are you talking about? Quoting the paper

> We evaluate Node2Vec and the Spectral Embedding technique via node classification with a Graph Convolutional Network

it seems that the results are also a function of the GCN, so you'd have to find out the parameters of the Node2Vec algorithm, and the architecture and parameters of the GCN aswell

**Comment by HaiQW** [comment]
I refer to 
`the pure node2vec embeddings of the cora dataset as well as the t-sne visualization of the embeddings`

In the quoted paper, the authors also evaluated the original node2vec model on the cora dataset.

**Comment by eliorc** [comment]
So if you are talking about visualization, obviously you are dependent on the t-SNE's algorithms parameters. Also t-SNE is not consistent, it is an iterative algorithm so getting the a visualization to look similar is dependent on things like the preplexity, random seed and more.
