### ISSUE TITLE
cannot import name 'Node2Vec' from 'node2vec'

### ISSUE THREAD

**Issue by chanlevan** [eliorc/node2vec#21]
Hi, 

I installnode2vec using pip install. However when I start the sample scripts from your example, it shows error: 
"from node2vec import Node2Vec
ImportError: cannot import name 'Node2Vec' from 'node2vec'"

Do you know why? 

My python version: 3.7.1
OS: tried both on Mac and Red Hat 7.6

Regards, 
Chan.

**Comment by eliorc** [comment]
I cannot replicate this issue - are you sure you installed it on the interpreter that is running this command?

**Comment by chanlevan** [comment]
I managed to build directly from the source code and it works now. So never mind.

**Comment by Lihengwannafly** [comment]
Oh, sorry, i meet this issue again.

**Comment by trbuser** [comment]
0

**Comment by trbuser** [comment]
Hello,
I am facing the same issu, but i can't fix it?
can someone help me, please?

here is the error that i have:

from node2vec import Node2Vec
ImportError: cannot import name Node2Vec
My python version: 3.6
OS: ubuntu 18.04

**Comment by chanlevan** [comment]
> Hello,
> I am facing the same issu, but i can't fix it?
> can someone help me, please?
> 
> here is the error that i have:
> 
> from node2vec import Node2Vec
> ImportError: cannot import name Node2Vec
> My python version: 3.6
> OS: ubuntu 18.04

Hi,

Last time I resolved it by cloning the repository and navigating to the code folder and put:

`pip install .`

It worked after that. Hope this help.

**Comment by trbuser** [comment]
> > Hello,
> > I am facing the same issu, but i can't fix it?
> > can someone help me, please?
> > here is the error that i have:
> > from node2vec import Node2Vec
> > ImportError: cannot import name Node2Vec
> > My python version: 3.6
> > OS: ubuntu 18.04
> 
> Hi,
> 
> Last time I resolved it by cloning the repository and navigating to the code folder and put:
> 
> `pip install .`
> 
> It worked after that. Hope this help.

Thanks for your response, i tried this, but it seems like it still doesn't work :/

**Comment by trbuser** [comment]
Hi!! i fixed it, thank you @chanlevan . I managed the path on /home/user/python3.9/lib.

**Comment by aphex-bin** [comment]
Hi,
I'm getting this same issue. I've installed node2vec from conda forge in a conda environment and when I try to run the example code in vscode I get this error:

ImportError: cannot import name 'Node2vec' from 'node2vec' (/anaconda/envs/node2vec/lib/python3.7/site-packages/node2vec/__init__.py)
