### ISSUE TITLE
Saving edge embeddings as KeyedVectors in Python 3

### ISSUE THREAD

**Issue by aamay** [eliorc/node2vec#22]
Hi there,

Thanks for implementing this great algorithm in Python 3. For me all is well and working except for saving the edge embeddings as KeyedVector. It keeps giving me this error

`'Word2VecKeyedVectors'` object has no attribute `'add'`

It works well with Python2, but not in Python 3.

Thanks!

**Comment by eliorc** [comment]
This library is for python3, can you supply code to reproduce the error ?

**Comment by aamay** [comment]
Thanks for your prompt response.

Nothing advanced actually. I used the code provided on the repository ReadMe file on 1K nodes graph.
Below are conda environment specs..
[spec-file.txt](https://github.com/eliorc/node2vec/files/3430975/spec-file.txt)

**Comment by eliorc** [comment]
What was the code for saving? It should be something like

```python3
edges_embs = HadamardEmbedder(keyed_vectors=model.wv)

edges_embs.as_keyed_vectors().save_word2vec_format(EMBEDDING_FILENAME)
```

**Comment by aamay** [comment]
exactly, and then I get this error:

`
AttributeError                            Traceback (most recent call last)
<ipython-input-172-cbaabb72b44f> in <module>
----> 1 edges_embs.as_keyed_vectors().save_word2vec_format(edge_embed_file)

~/anaconda3/envs/graphs/lib/python3.7/site-packages/node2vec/edges.py in as_keyed_vectors(self)
     68         # Build KV instance
     69         edge_kv = KeyedVectors(vector_size=self.kv.vector_size)
---> 70         edge_kv.add(
     71             entities=tokens,
     72             weights=features)

AttributeError: 'Word2VecKeyedVectors' object has no attribute 'add'
`

**Comment by eliorc** [comment]
I can't seem to reproduce this error, it works fine for me...

I saw the issue RaRe-Technologies/gensim#2268, and I can see there that reinstalling helped - can you try reinstalling in a new virtual environment?

**Comment by aamay** [comment]
I created a new environment with python=3.6 and it worked well. Out of curiosity I upgraded it to python 3.7, and produced the same error.
Thanks Elior!
