### ISSUE TITLE
Why is the stage of Generating walks is 0%?

### ISSUE THREAD

**Issue by Lihengwannafly** [eliorc/node2vec#25]
the code:
```
graph = nx.from_pandas_edgelist(
    answer_info,
    "author_id",
    "question_id",
    "like_nums",
)

node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=100, workers=10,
                    temp_folder="/data/zhihu/node2vec")  # Use temp_folder for big graphs
model = node2vec.fit(window=10, min_count=1,
                     batch_words=4) 
```
and the log:
```
Computing transition probabilities: 100%|██████████| 2188614/2188614 [30:54<00:00, 1180.22it/s]
Generating walks (CPU: 4):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 3):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 5):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 2):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 6):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 7):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 8):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 9):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 1):   0%|          | 0/10 [00:00<?, ?it/s]
Generating walks (CPU: 10):   0%|          | 0/10 [00:00<?, ?it/s]
```

**Comment by Lihengwannafly** [comment]
temp_folder="/data/zhihu/node2vec"

> the code:
> 
> ```
> graph = nx.from_pandas_edgelist(
>     answer_info,
>     "author_id",
>     "question_id",
>     "like_nums",
> )
> 
> node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=100, workers=10,
>                     temp_folder="/data/zhihu/node2vec")  # Use temp_folder for big graphs
> model = node2vec.fit(window=10, min_count=1,
>                      batch_words=4) 
> ```
> 
> and the log:
> 
> ```
> Computing transition probabilities: 100%|██████████| 2188614/2188614 [30:54<00:00, 1180.22it/s]
> Generating walks (CPU: 4):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 3):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 5):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 2):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 6):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 7):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 8):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 9):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 1):   0%|          | 0/10 [00:00<?, ?it/s]
> Generating walks (CPU: 10):   0%|          | 0/10 [00:00<?, ?it/s]
> ```

I drop temp_folder and reduce data size, then the code works. Do I set wrong temp_folder?

**Comment by eliorc** [comment]
Are you sure nothing happens when it is on 0? Coulnd't it be it just takes a while to transfer the graph to all the other CPUs? Assuming the data is big it could take a while
