### ISSUE TITLE
A question about random parameter

### ISSUE THREAD

**Issue by leaveszuki** [eliorc/node2vec#26]
Hello @eliorc :
      Firstly, thanks for your works about Node2Vec in python, which makes this algorithm using more eaier. Now I am trying to generate 10 sets of node vectors, but I get the same data every time. What parameter could I set to get different data? If you could provide advice, I would be very grateful. The Following is the code and the log.
```
for epoch in range(10):
        node2vec = Node2Vec(
                            graph, 
                            dimensions=2, 
                            walk_length=5, 
                            workers=1,
                            p = 17.8,
                            q = 0.001)
        model = node2vec.fit(window=2, min_count=1, batch_words=6)
        print(model['2'])
```

> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 1999.99it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 434.76it/s]
> D:\Business\GNN\node2vec_pro\test_para.py:31: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
>   print(model['2'])
> [-0.20316663 -0.14337409]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 3000.22it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 499.97it/s]
> [-0.20315658 -0.14337872]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 2999.86it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 384.59it/s]
> [-0.2032127  -0.14340548]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 2999.86it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 416.64it/s]
> [-0.20316675 -0.1433859 ]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 2999.86it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 555.52it/s]
> [-0.20316663 -0.14337409]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 1999.99it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 526.29it/s]
> [-0.2031702  -0.14337513]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 2999.86it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 476.16it/s]
> [-0.20327514 -0.14351842]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 2999.86it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 588.20it/s]
> [-0.20317353 -0.1433965 ]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 2999.86it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 555.52it/s]
> [-0.20317145 -0.14337693]
> Computing transition probabilities: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 2999.86it/s]
> Generating walks (CPU: 1): 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 384.59it/s]
> [-0.20317672 -0.14338204]
> Press any key to continue . . .

**Comment by eliorc** [comment]
You should set a different seed each time you call `fit`, e.g. `model = node2vec.fit(window=2, min_count=1, batch_words=6, seed=epoch)`

**Comment by marcovarrone** [comment]
Hello,
I am actually encountering the opposite problem. I cannot manage to reproduce the same embedding on multiple runs, even by manually setting the seed.

```python
graph = nx.from_numpy_array(adj)
for _ in range(2):
    node2vec = Node2Vec(graph, dimensions=8, walk_length=11, num_walks=19, p=1.0, q=1.0,
                                         workers=1)

    model = node2vec.fit(window=10, min_count=1, batch_words=4, seed=1)
    print(model['2'])
```

> Computing transition probabilities: 100%|████| 253/253 [00:01<00:00, 237.58it/s]
Generating walks (CPU: 1): 100%|████████████████| 19/19 [00:01<00:00, 13.06it/s]
[-1.6140815  -0.37363848  0.513672   -0.58913547 -0.73540115  0.01850495
  2.4176047   3.8480723 ]
Computing transition probabilities: 100%|████| 253/253 [00:01<00:00, 235.14it/s]
Generating walks (CPU: 1): 100%|████████████████| 19/19 [00:01<00:00, 12.04it/s]
[-1.07654   -1.653176   1.4607193 -2.9491777 -0.9649378 -1.3609339
 -0.503423   2.9037342]

I tried to omit the seed parameter and also to set the seed from numpy with np.random.seed() but the embedding is always different.
Thank you for your work!

**Comment by eliorc** [comment]
When you don't set it it is "kind of" reproducible, notice that the results are very close (you can verify that programatically using numpy's `is_close` method).

I can't tell how to reproduce down to the floating point, which is a wide problem in neural networks in general
