### ISSUE TITLE
set the workers more than 1, it will cause the TerminatedWorkerError

### ISSUE THREAD

**Issue by abc3436645** [eliorc/node2vec#27]
PC memory:128GB
node2vec = Node2Vec(G, dimensions=100, walk_length=30, num_walks=100, workers=10)

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {EXIT(2), EXIT(2), EXIT(2), EXIT(2), EXIT(2), EXIT(2), EXIT(2), EXIT(2)}

when I set the worker=1, it runs successfully, but it runs so slowly

**Comment by eliorc** [comment]
Please look at the `temp_folder` argument in the documentation on the first page, and let me know if that solved your problem
