### ISSUE TITLE
Memory Error 

### ISSUE THREAD

**Issue by SihamAmarouche** [eliorc/node2vec#28]
The following code almost takes all of the memory.
node2vec = Node2Vec(G_fb, dimensions=emb_size, walk_length=80, num_walks=10, workers=4)

I have processed only 7 thousand nodes and then got memory error.

Here is the error:
`MemoryError Traceback (most recent call last)
in ()
4
5 for emb_size in [32, 128]:
----> 6 node2vec = Node2Vec(G_fb, dimensions=emb_size, walk_length=80, num_walks=10, workers=3) # Use temp_folder for big graphs
7 model = node2vec.fit(window=10, min_count=1,batch_words=4)
8 model.wv.save_word2vec_format("mypath/%s_%d.deepwalk"%(graph_name,emb_size))

...site-packages\node2vec\node2vec.py in init(self, graph, dimensions, walk_length, num_walks, p, q, weight_key, workers, sampling_strategy, quiet, temp_folder)
68 self.require = "sharedmem"
69
---> 70 self._precompute_probabilities()
71 self.walks = self._generate_walks()
72

...site-packages\node2vec\node2vec.py in _precompute_probabilities(self)
117 if current_node not in first_travel_done:
118 first_travel_weights.append(self.graph[current_node][destination].get(self.weight_key, 1))
--> 119 d_neighbors.append(destination)
120
121 # Normalize

MemoryError:`

Is there a way to process big graphs with a lot of nodes without getting memory error?
I know that I can use temp_folder for that but I don't know how I can apply it?

**Comment by eliorc** [comment]
`temp_folder` should be a path to a directory where you can write to, and has enough memory available - to apply it just pass a path as string. `temp_folder` is relevant only for parallel work, you can try to run on a single process and see if it works (obviously slower) by passing `workers=1`

**Comment by SihamAmarouche** [comment]
Thanks very much :)
