### ISSUE TITLE
Inputs should be in the form of..?

### ISSUE THREAD

**Issue by ChoYoungSeo** [eliorc/node2vec#29]
I want to put the float number weighted graph as edgelist for the input, but apparently

it doesn't work. Can you guide me?

**Comment by eliorc** [comment]
Taken from the README on the repo main page


> ### `node2vec.Node2vec`
> #### `Node2Vec` constructor:
> 
> graph: The first positional argument has to be a **networkx graph**. Node names must be all integers or all strings. On the output model they will always be strings.
