### ISSUE TITLE
can u guide me how to use the temp folder in Mac?

### ISSUE THREAD

**Issue by ChoYoungSeo** [eliorc/node2vec#30]
Actually I have no background on the hardware and I cannot find the way to deal with the big graphs.

Thanks for helping me

**Comment by eliorc** [comment]
Just point it to a folder on your machine which has enough space, it should work (never tested it myself on Mac)

**Comment by ChoYoungSeo** [comment]
for example, just like this? :

node2vec = Node2Vec(graph, dimensions=20, walk_length=10, p = 1, q = 0.5, num_walks=50, workers=4,temp_folder = '/tmp')

**Comment by eliorc** [comment]
Exactly

**Comment by ChoYoungSeo** [comment]
I've done it but still facing the lack of RAM memory,,, any other options or things should I do..?

**Comment by eliorc** [comment]
If you have enough space in `/tmp` and you still have memory issues, there are no other options for dealing with large graphs in the current implementation

**Comment by ChoYoungSeo** [comment]
Thnx, anyway, I'm really curious if it really works on the big graph.

I used the graph of 10000 nodes and to compute the transition prob, it takes about 150s per iteration.

Is it normal or I did something wrong?

**Comment by eliorc** [comment]
The time is more related to the number of edges from each node, more than to the number of nodes.

I have ran this package on graphs with 35K~ nodes and roughly 4x time the edges and it was fine (without using `temp_folder`). But I was running on a very strong machine with 16 cores and 256GB RAM.

Could be that the specs of the host you are running your code on is not sufficient for the speed you expect
