### ISSUE TITLE
Will node2vec return same vector for same node V?

### ISSUE THREAD

**Issue by stormlovetao** [eliorc/node2vec#31]
Hi There,

I am new to node2vec, and have a quick question: for different runs, will node2vec return same vector for a same node V? given the default parameters. I am not very sure about this because the random walk is a random process. 
Looking forward to your reply. Thanks!

Best,
Tao

**Comment by eliorc** [comment]
No, as you said the algorithm has a random process in it.

I haven't tried, but you can try to fix the python and numpy seeds and see if you manage to replicate
