### ISSUE TITLE
Node2Vec on Bipartite Graph outputs similar nodes from both node set

### ISSUE THREAD

**Issue by AmalNammouchi** [eliorc/node2vec#34]
1)I tried to apply Node2Vec on Bipartite graph, but I want the input to be a node from the node Set A and the output to be nodes from the node set B. I tried to change the parameters (walk_length and num_walks) but I always get output nodes from both the node set og the graph.
How can I do that while letting the model learn from all the graph?
2)How can I apply node2vec on dynamic Graphs?

**Comment by eliorc** [comment]
1. Outputs of node2vec are for all nodes in the graph, you can't filter out nodes, unless you make the walk probability to/from them to zero, which is equivalent to just removing them from the graph.
2. Much like word2vec only learns embeddings for words it has seen and treats unmet words as OOV, you can try to take the same approach

**Comment by AmalNammouchi** [comment]
when I add a node to my graph which has no link on it (it s like a new node that still has no link), and then apply node2vec to my graph and  check the most similar nodes to my node, it outputs some results, but I am not sure according to what exactly it outputed that result, according to what those outputed nodes are similar to my unconnected node?
