### ISSUE TITLE
longer time for computing transition probabilities for each node.

### ISSUE THREAD

**Issue by urmi22** [eliorc/node2vec#35]
I have a graph of 141382 nodes and 49296336 edges. But computation of transition probabilities for each node is taking a huge time. Status of my code is as follows:
`Computing transition probabilities:   0%|                    | 44/141382 [10:46<607:39:02, 15.48s/it]`
Is there any way out to speed up the execution?

**Comment by eliorc** [comment]
Nope, I have listed in the TODO of the repo a parallel implementation of the transition probability, but there is none yet

So I don't have any solution for this ATM

**Comment by mustfkeskin** [comment]
do you have found any solution

**Comment by eliorc** [comment]
> do you have found any solution

Nope
