### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'temp_folder'

### ISSUE THREAD

**Issue by CoGore** [eliorc/node2vec#37]
`n2v=Node2Vec(G, dimensions=100, workers=4, p=0.25, q=0.25, temp_folder='F:/n2v_v1/temp/')`

I tried to set a temp_folder but an error appeared as below saying there isn't such a parameter. Is this parameter still available now?

TypeError                                 Traceback (most recent call last)
<ipython-input-12-242fdf507e8b> in <module>
----> 1 n2v=Node2Vec(G, dimensions=100, workers=4, p=0.25, q=0.25, temp_folder='F:/n2v_v1/temp/')

TypeError: __init__() got an unexpected keyword argument 'temp_folder'

**Comment by eliorc** [comment]
Are you sure you are on the latest version? use `import node2vec; print(node2vec.__version__)` to see the version you are on
