### ISSUE TITLE
How to load a saved model?

### ISSUE THREAD

**Issue by LinChen-65** [eliorc/node2vec#40]
Hi, I save the model by:

_model.save('./test1.model')_

But when I tried to reload it and wrote:

_model = node2vec.load('./test1.model')_

I got an AttributeError: 'Node2Vec' object has no attribute 'load'.

I'm wondering what is the right way to reload my model. 
Thank you!

**Comment by eliorc** [comment]
Notice that `fit` returns a `gensim.models.Word2Vec` instance so you can refer to the documentation [here](https://radimrehurek.com/gensim/models/word2vec.html) to see how to use this object. If you used `model.save` (and not `model.wv.save`) so you have to load it as follows

```python3
from gensim.models import Word2Vec

loaded_model = Word2Vec.load('./test1.model`)
```
