### ISSUE TITLE
Tested with Large Graphs?

### ISSUE THREAD

**Issue by karrtikiyer** [eliorc/node2vec#41]
Hi,
I am trying to use this library on a multigraph, which has around 28K nodes and 3000000 edges, it is a weight graph.
The Node2Vec constructor runs for around 5-7 hours after which kernel restarts. I am running it on MacBook Pro with 32 GB Ram and 6 cores. I am trying to run this with a step size of 6 and number of walks as 100. Number of workers is set to 3.
Is there a way I can debug this issue and understand why this might be happening? Can you please advise.
Thanks,
Karrtik

**Comment by louisabraham** [comment]
I suspect it is because the memory usage of the probability precomputation is quadratic in the number of edges. My version does not have such limitation and also runs faster: https://github.com/louisabraham/fastnode2vec

**Comment by eliorc** [comment]
Indeed seems like a memory issue, did you try using the `temp_dir` argument?

**Comment by karrtikiyer** [comment]
Oh thanks I wasn't aware of that argument, I am trying it with that argument and also compare the results with fastnode2vec as suggested by @louisabraham  above.

**Comment by louisabraham** [comment]
@karrtikiyer were you able to produce some comparisons?

**Comment by karrtikiyer** [comment]
@louisabraham : Sorry for the delay in response. I was away for last couple of weeks, please give me some more time before I can finish this work.
