### ISSUE TITLE
Running Node2Vec on Google Colab is very slow

### ISSUE THREAD

**Issue by ZihanChen1995** [eliorc/node2vec#42]
Hi,

Thank you so much for this handy library. I'm trying to implement the node2vec on Google Colab. However, when I embed a sample graph with 10,000 edges, it takes more than 1 hour 40 min to finish (When implementing on 80,000 edges, it takes more than 4 hours). I've used the tem_folder to avoid memory issues. Since I plan to implement it on a real-world dataset, which includes more than 100,000,000 edges, may I ask is there any way that I can speed up the training process without sacrificing much performance?

The parameter I choose is following:
```
# the dimension of node embedding
embedding_dimension = 50,

 # to avoid too big graph
temp_folder = temp_folder_path,

# the lenght of walk
walk_length=80,

# number of walks
num_walks=10,

# p,q
p=1, 
q=1,

# worker number
workers=4,

# window size
window=10,
min_count=1,

# batch size
batch_words=4
```

Thank you a lot in advance!

**Comment by eliorc** [comment]
Unfortunately no, I can't see any way using this implementation that you can speed this up - only speedup that is possible is through the workers, so if you are already using them nothing more can be done.
`temp_folder` is only for the sake of OOM issues, it actually slows the process (memory IO) but is essential when your graph is very big.

**Comment by ZihanChen1995** [comment]
I see. Thank you for your reply.
