### ISSUE TITLE
Does node2vec take into account node attributes?

### ISSUE THREAD

**Issue by UCRajkumar** [eliorc/node2vec#43]
I have a networkx such that each node name is a string and its data is a dict with the following format `{'type' : 'class A'}`.
So essentially an example of a node is
`NodeDataView({'dog': {'type': 'class A'}, ...)`

Will this library take into account this data attribute of the node?

**Comment by eliorc** [comment]
What do you mean by take into account? These are not going to be used in any way for the embedding creation if that is your question

**Comment by UCRajkumar** [comment]
Ahh, I see. Got it, thank you
