### ISSUE TITLE
Does Node2Vec code support community detection?

### ISSUE THREAD

**Issue by nissou91** [eliorc/node2vec#44]
Hello,

I am new to Node2Vec, I have succeeded in creating nodes' embeddings of a directed weighted graph. Now I want to know if this code can achieve community detection and if so how to do it? because if I am not mistaken, in the paper they mention that it is possible to use Node2Vec to do community detection. 

Thanks in advance.

**Comment by ruanchaves** [comment]
Save the embeddings and then run HDBSCAN. [Follow this tutorial](https://hdbscan.readthedocs.io/en/latest/basic_hdbscan.html).
