### ISSUE TITLE
Load model and embedding

### ISSUE THREAD

**Issue by hxtruong** [eliorc/node2vec#45]
Hi eliorc,
I am using Node2vec for my project. It's good library for me.
But I got stuck when load model and embedding node after saving. I _must_ run `node2vec.fit` to have  `node2vec_model.wv.load_word2vec_format(filename)`. If not, I can not get `node2vec_model`. I think this is bug, because I always wast time to train from scratch by `fit` function without load immediately.
This is my code:
```python
node2vec = Node2Vec(graph=graph,
                        dimensions=embedding_dim,
                        walk_length=80,
                        num_walks=20,
                        workers=2)  # Use temp_folder for big graphs
node2vec_model = node2vec.fit()
if is_load_emb:
    embedding = node2vec_model.wv.load_word2vec_format(filename)
else:
     embedding = [np.array(node2vec_model[str(u)]) for u in sorted(graph.nodes)]
     if filename is not None:
        node2vec_model.wv.save_word2vec_format(filename)
```
Thanks

**Comment by eliorc** [comment]
Yes you can, simply use `gensim` directly

```python3
from gensim.models import KeyedVectors

embedding = KeyedVectors.load_word2vec_format(...)
```
