### ISSUE TITLE
Saving corpus in text file

### ISSUE THREAD

**Issue by Mahmedturk** [eliorc/node2vec#47]
Hi,

Is there a way to save the corpus in a text file which is generated as a result of random walks?

**Comment by eliorc** [comment]
Do you mean you want to access the results of the walks? If so, after running the `node2vec = Node2Vec(...)` (the constructor) you can access the walks in `node2vec.walks` and do whatever you wish to do with them

**Comment by Mahmedturk** [comment]
Thanks!
