### ISSUE TITLE
If I don't use Anaconda but in Windows Environment, does the code work?

### ISSUE THREAD

**Issue by Xshelton** [eliorc/node2vec#5]
Does not work on Anaconda + Windows?
If I don't use Anaconda but in Windows Environment, does the code work?
kinda of confused.

**Comment by eliorc** [comment]
I really can't tell, I'm working on an Ubuntu environment, so I can't test it.
But looking at the issues, all of the people who reported problems are on Windows, and specifically have problems with the `joblib`'s way of parallel execution.

**Comment by eliorc** [comment]
You might want to see if the code in the warning in [this link](https://pythonhosted.org/joblib/parallel.html), solved the issue

**Comment by Xshelton** [comment]
yep I have tested the code, I installed gensim,qdm,joblib ,and run in Win-Environment without Anaconda, and guess what? you were right about the 'joblib' issue.
here 👍is the detailed error..     
File "C:\...\Python36\lib\site-packages\joblib\externals\loky\_base.py", line 382, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by eliorc** [comment]
`joblib` is only used for parallel computation, if you don't need it to scale, you can try on the windows machine to run it on a single process and see if it crashes or not.

Just call `node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=200, workers=1)`, specifically the argument `workers=1` will cause it to run on a single process

**Comment by Xshelton** [comment]
okay ,I will test it now.

**Comment by Xshelton** [comment]
well ,it works. although it takes sometime(about one hour for 100 node), but at least it works now in Windows -environment .THX XD

**Comment by eliorc** [comment]
:+1:
