### ISSUE TITLE
Computing transition probabilities extremely slow - not parallel

### ISSUE THREAD

**Issue by davidfstein** [eliorc/node2vec#51]
I am running n2v on a graph with around 40 million edges with the default values from the example in the readme. The Computing transition probabilities step is estimated to take around 533 hours and is running on only one CPU. I have workers set to 30. Is it possible to parallelize this or speed it up some other way?

**Comment by eliorc** [comment]
Workers should be as the number of cores - do you have 30? You can set it to `-1` for using all cores

About speeding it up, one of the caveats of this package is that we don't have yet a parallel probability computing ability - so it is serial... Until we'll have that, there is nothing else you can do to speed up the training :/

**Comment by davidfstein** [comment]
Yeah, I'm running on a cluster with 80 cores. Do you think its possible to parallelize that step? Maybe worth adding as a feature (even if a very distant one) if so.

**Comment by AndreaPrati98** [comment]
@ldorigo I am wondering it too.

I love the simplicity of this library but without that kind of parallelism there is no way I can use it my very large graph 😭 .
