### ISSUE TITLE
Is the trained word2vec really skip-gram by default? or is it CBOW?

### ISSUE THREAD

**Issue by kkteru** [eliorc/node2vec#54]
Thanks for putting this together!

The variable naming indicates that the trained word2vec model within node2vec model is a skip-gram model. However, the [default setting](https://github.com/RaRe-Technologies/gensim/blob/eff2faf0eca0da7ad41d20e17b5ef46c11874148/gensim/models/word2vec.py#L281) of gensim's Word2Vec is CBOW. Having said that, one can easily pass the required parameter to chose a skip-gram model instead of CBOW.

This is a tiny technical detail which makes the default setting of this code different from the original node2vec which explicitly trains a skip-gram model. Perhaps the users should be aware of that. Or did I miss something?

**Comment by eliorc** [comment]
You are absolutely right, the paper indeed uses skip-gram, and gensim defaults to CBOW, I approved it and will release a new version shortly
