### ISSUE TITLE
Clarification about the walks from node2vec

### ISSUE THREAD

**Issue by amjass12** [eliorc/node2vec#56]
Hi! 

Just a quick question on the clarification on the corpus for further downstream analysis. after running node2vec with the following parameters:

`node2vec = Node2Vec(graph, dimensions=128, walk_length=30, num_walks=10, workers=1) `

I then access the walks as I need them in a text file:

`walks = node2vec.walks`

Can I clarify - that in the entire corpus of text, should be 10 sets of 'sentences' for each node which each contain 30 words in that sentence? (word being the nodes around them)

so it should be saved to reflect each set of 30 nodes in the list which can be saved as follows?:

```
with open(f'walks_for_{graph.name}.txt','w')as f:
        for walk in node2vec.walks:   
            for node in walk:
                f.write(node + " ")
            f.write("\n")
```

thank you. I want to be sure the format is correct for embedding as I want to embed using another package and want to check that this is what would be entered in to the model as the corpus for Node2Vec also?

**Comment by eliorc** [comment]
Yes, exactly that. Notice that some walks might be shorted, it depends on how big is your graph and if its directed or not. For examplel if you have a node with out degree of 0 the walks going out from him would not reach 30 obviously :)

**Comment by amjass12** [comment]
Hi @eliorc ,

Thank you for confirming! 

Interesting on your second point. I have a follow up question... In theory this makes sense, however, I always generate 'sentences' of 30 nodes... I remove single nodes with no edges.. however there are plenty of nodes with only one edge connected to one other node... Is it possible to expect that even for these nodes there would be 30 nodes in the walk?.. Can node2vec jump to other parts of the graph as part of the biased random walk? 

The graph is undirected.. and the graph I put in to node2vec is a networkx graph...

I am wondering if I might be doing something wrong along the way.. I always have a corpus of sentences that contain always 30 words in each sentence...

**Comment by eliorc** [comment]
If the graph is undirected then you even a graph with only two nodes and one edge between them can generate a walk of length 30, since you can go back and forth between these two nodes

**Comment by amjass12** [comment]
@eliorc ,

Thank you - yes I can confirm this is exactly what is happening - so I don;t have shortened sentences but they are length 30 with word1 and word2 repeated of length 30... 

I have one last question, which is, when i fit the model after the walk - 2 nodes that are only connected by one edge - when i do `model.most_similar('word1')`

I see that the node it is connected to is actual 0.9 similar which is correct - however there are other nodes around it which are also 0.9 similar... however.. these 2 nodes are disconnected from the whole graph and only connected to each other... what explains their similarity to other nodes? is it their physical embedding position?

```
 [('word1', 0.9998584389686584),  <- node1
 ('word2', 0.9973844289779663), <-node2
 ('word3', 0.9973589777946472), <-not connected to node1 or node2
 ('word4', 0.9973569512367249), <-not connected to node1 or node2
 ('word5', 0.9973028898239136)] <-not connected to node1 or node2
```
thanks!

**Comment by eliorc** [comment]
Seems like the hyperparameters are not adequate for the data you supplied...

its really hard to pinpoint what, but if you are using very small data for example you can get results that don't make sense

**Comment by amjass12** [comment]
ok yes! i have played around with some hyperparams - window size etc, and this now makes sense!
```

[('word1', 0.9996885657310486),
 ('word2', 0.5823773145675659),
 ('word3', 0.5817686319351196),
 ('word4', 0.4863593876361847),
 ('word5', 0.48261046409606934)]
```

thank you for taking the time to answer all of my questions!
