### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by zhuzhu-lu** [eliorc/node2vec#62]
Hi,thanks for your contribution.My graduation project will use this algorithm and be used for later community detection,now I encountered some problems when running this code.
1.What does the EdgeEmbedder use for?
2.What's the difference bettwen the NODE_EMBEDDING and EDGES_EMBEDDING,do they need diffrent inputs?eg. For complex network data sets such as facebook_combined.txt or karate.edegelist,should it use node_embedding or edges_embedding?
3.I got an error 'MemoryError: Unable to allocate 1.11 KiB for an array with shape (142,) and data type float64',I guess it's beacause my graph is too big,but I don't know where should I add Var "temp_folder" to solve this problem.

**Comment by eliorc** [comment]
1. `EdgeEmbedder` is for embedding edges (rather than nodes)
2. I'm not sure what you mean NODE_EMBEDDING and EDGES_EMBEDDING
3. `temp_folder` can be passed ot the `Node2Vec` initialization method

**Comment by zhuzhu-lu** [comment]
> 1. `EdgeEmbedder` is for embedding edges (rather than nodes)
> 2. I'm not sure what you mean NODE_EMBEDDING and EDGES_EMBEDDING
> 3. `temp_folder` can be passed ot the `Node2Vec` initialization method

Thank u for your reply.
For the 2th question,I mean what's the difference bettwen embedding nodes and edeges?I don't see this in aditya-grover/node2vec(From original author).

**Comment by zhuzhu-lu** [comment]
when I add Var "temp_folder",I still got an MemoryError as followed:
Traceback (most recent call last):
  File "D:/Users/PycharmProjects/n2v/runalg.py", line 23, in <module>
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\node2vec\node2vec.py", line 72, in __init__
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\node2vec\node2vec.py", line 117, in _precompute_probabilities
MemoryError

/(ㄒoㄒ)/~~

**Comment by eliorc** [comment]
About (2), section 3.3 talks about edge embeddings

about the memory error, I'm not sure what is wrong - do you point to a folder which has enough disk space?

**Comment by zhuzhu-lu** [comment]
I am sure that I pointed to a folder which has enough disk space.But I still got the same error when I use this algorithm on a dataset containing more than 80,000 nodes.But it works fine on a dataset containing more than just 10,000 nodes.

**Comment by zhuzhu-lu** [comment]
I just tested the dataset which containg 80,000 nodes on 'aditya-grover/node2vec',and it worked out fine.But I still got memoryerror when running your code.
Computing transition probabilities:  81%|████████  | 66024/81306 [20:36<5:46:35,  1.36s/it]Exception ignored in: <generator object tqdm.__iter__ at 0x1B256BC0>
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\tqdm\std.py", line 1193, in __iter__
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\tqdm\std.py", line 1299, in close
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\tqdm\std.py", line 1492, in display
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\tqdm\std.py", line 1148, in __str__
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\tqdm\std.py", line 484, in format_meter
MemoryError: 
Traceback (most recent call last):
  File "D:/Users/PycharmProjects/n2v/runalg.py", line 23, in <module>
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\node2vec\node2vec.py", line 72, in __init__
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\node2vec\node2vec.py", line 120, in _precompute_probabilities
MemoryError: Unable to allocate 1.11 KiB for an array with shape (142,) and data type float64

**Comment by eliorc** [comment]
Try running with `workers=1`, if it works on aditya's I guess you get memory error for parallelisation

**Comment by zhuzhu-lu** [comment]
I did running with workers=1,but it still didn't work fine on this code.I guess I might get error for parallelisation.Is there a way out?

**Comment by eliorc** [comment]
Can't see why it doesn't work, maybe you should paste your whole code snippet?

**Comment by zhuzhu-lu** [comment]
import networkx as nx
from node2vec import Node2Vec
# FILES
EMBEDDING_FILENAME = './twitter_embeddings.emb'
INPUT = './twitter_combined.txt'
# Create a graph
graph = nx.read_edgelist(INPUT, nodetype=int,  data=(('weight',float),), create_using=nx.DiGraph())

#Precompute probabilities and generate walks - **ON WINDOWS ONLY WORKS WITH workers=1**
node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=200, workers=1, p=1, q=1,temp_folder="E:\\tmp_data")  # Use temp_folder for big graphs

# Embed nodes
model = node2vec.fit(window=10, min_count=1, batch_words=4)  # Any keywords acceptable by gensim.Word2Vec can be passed, `dimensions` and `workers` are automatically passed (from the Node2Vec constructor)

# Look for most similar nodes
model.wv.most_similar('2')  # Output node names are always strings

# Save embeddings for later use
model.wv.save_word2vec_format(EMBEDDING_FILENAME)

**Comment by zhuzhu-lu** [comment]
'''python
import networkx as nx
from node2vec import Node2Vec

FILES
EMBEDDING_FILENAME = './twitter_embeddings.emb'
INPUT = './twitter_combined.txt'

Create a graph
graph = nx.read_edgelist(INPUT, nodetype=int, data=(('weight',float),), create_using=nx.DiGraph())

#Precompute probabilities and generate walks - ON WINDOWS ONLY WORKS WITH workers=1
node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=200, workers=1, p=1, q=1,temp_folder="E:\tmp_data") # Use temp_folder for big graphs

Embed nodes
model = node2vec.fit(window=10, min_count=1, batch_words=4) # Any keywords acceptable by gensim.Word2Vec can be passed, dimensions and workers are automatically passed (from the Node2Vec constructor)

Look for most similar nodes
model.wv.most_similar('2') # Output node names are always strings

Save embeddings for later use
model.wv.save_word2vec_format(EMBEDDING_FILENAME)

**Comment by zhuzhu-lu** [comment]
'''python
import networkx as nx
from node2vec import Node2Vec

#FILES
EMBEDDING_FILENAME = './twitter_embeddings.emb'
INPUT = './twitter_combined.txt'

#Create a graph
graph = nx.read_edgelist(INPUT, nodetype=int, data=(('weight',float),), create_using=nx.DiGraph())

#Precompute probabilities and generate walks
node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=200, workers=1, p=1, q=1,temp_folder="E:\tmp_data") # Use temp_folder for big graphs

#Embed nodes
model = node2vec.fit(window=10, min_count=1, batch_words=4) # Any keywords acceptable by gensim.Word2Vec can be passed, dimensions and workers are automatically passed (from the Node2Vec constructor)

#Look for most similar nodes
model.wv.most_similar('2') # Output node names are always strings

#Save embeddings for later use
model.wv.save_word2vec_format(EMBEDDING_FILENAME)

**Comment by eliorc** [comment]
Which line throws the error?

**Comment by zhuzhu-lu** [comment]
error in this line:
node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=200, workers=1, p=1, q=1,temp_folder="E:\\tmp_data")

File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\node2vec\node2vec.py", line 72, in init
File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\node2vec\node2vec.py", line 120, in _precompute_probabilities
MemoryError: Unable to allocate 1.11 KiB for an array with shape (142,) and data type float64

**Comment by eliorc** [comment]
I really can't identify the problem... a little googling sent me here, can you try this solution?
https://stackoverflow.com/a/58686879/5368083

**Comment by zhuzhu-lu** [comment]
okay,I will try this solution.Thank you for your patient answers，then I will just close this issue.😊
