### ISSUE TITLE
A question for my internship

### ISSUE THREAD

**Issue by Floriangarcia7** [eliorc/node2vec#64]
Hi,

Thank you for your contribution. I have a question for you.
For my internship, I use your implementation of node2vec.
For context, my nodes are cells that have attributes like width and height.

My code is :
```python
graph = nx.read_edgelist(edgelist_filename, nodetype=int)

attributes = {0: {"width": 2.56, "heigth": 5.23}, 1: {"width": 5.25, "heigth": 12.89}, 2: .......}
nx.set_node_attributes(graph, attributes)

node2vec = Node2Vec(graph, dimensions=dim, walk_length=30, num_walks=200, workers=4)
...... #and so on as in the readme usage section
```

So my question is: Will these attributes be taken into account by your implementation to generate nodes and edges embeddings ?

The code works correctly but I don't know if my attributes are well taken into account.

Thanks !

**Comment by Floriangarcia7** [comment]
After looking deeper into your implementation, tell me if I'm wrong but I noticed that in the file "node2vec.py", you work on the weights of the nodes.
So, instead of working on the weights, I would have to do a similar work to take into account my two attributes which are the width and height.

If you have an idea of how to do this, I'm interested.

Thank you !

**Comment by eliorc** [comment]
No, it won't take into account your attributes

If you want to use one of them as weight, use the `weight_key` parameter in `Node2Vec.__init__`

**Comment by Floriangarcia7** [comment]
Ok thanks.
I will try to use the area of my attributes, i.e. (width x height) as a weight for each node.

Is doing this enough to use the node weights?
```python
for each node n
    graph.nodes[n]['weight'] = area
node2vec = Node2Vec(graph, dimensions=dim, walk_length=30, num_walks=200, workers=4, weight_key='weight')
```
Using the `weight_key` parameter in `Node2Vec.__init__`

**Comment by eliorc** [comment]
yeah, this looks okay

**Comment by Floriangarcia7** [comment]
OK, thanks a lot for your help !

So, I close the issue ticket.
