### ISSUE TITLE
testing with link prediction

### ISSUE THREAD

**Issue by alamirah93** [eliorc/node2vec#65]
Hello dear,
I have questions, now the code is work will and I tried to embed deferent graphs.
But I want to test and evaluate it by doing some tasks like classification, link prediction or node reconstruction.
Any one of them.
But I tried many time and searched for any efficient library or code, I didn't find any.

May you help me to suggest one that compatible with this library?

Also does this library accept .mat data set ? I tried blogcatalog.mat but I get 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 132: invalid start byte
`

**Comment by eliorc** [comment]
I'm not sure I understand your question, the only question I did understand is about `.mat` file - regarding that you should check how `networkx` deals with `.mat` files, because the input to `node2vec` is a `networkx.Graph` so it doesn't really matter from which file it was generated

**Comment by alamirah93** [comment]
Thanks

I mean how did you evaluate the performance ?

**Comment by alamirah93** [comment]
Plese help me

**Comment by eliorc** [comment]
Embedding's performance can not be evaluated without a task... You can see on the original paper for example, when evaluating the quality of embeddings, you compare them with other embeddings using the same downstream model and task

Evaluating embeddings on their own is not something that as far as I know is possible in a robust way. You can manually inspect the resulting space using neighbors queries, and visualizations on lower dimensions and stuff like that.
