### ISSUE TITLE
skip-gram implementation and node2vec walks

### ISSUE THREAD

**Issue by amjass12** [eliorc/node2vec#67]
Hi!

I have two questions for clarification - The source code seems clear to me but i would like to confirm. 

I am generating walks on an nx graph which i will pass in to a different tool for the skip-gram implementation of w2v (reason for this is its a tool that aligns different word embeddings to look at temporal changes in words - I am using this for graphs). 

walks are generated as follows:

```
n2v = Node2Vec(graph, dimensions=64, walk_length=50, num_walks=100, quiet=True, workers=1, seed=1)
walks = n2v.walks

```
same for all other graphs - questions are:

1. the dimension argument is strictly for the subsequent `.fit` method correct? it doesn't have any influence on the walks? The source code suggests the self.dimension are only for the fit method. This would mean then that I can chose the dimensions in need in the second tool in their `.fit` method

2. Is the skip-gram implementation in the `.fit` altered in any way? or is it just pure gensim word2vec implementation of skip-gram? This one is less clear to me in the source code - it doesn't appear to be changed but need to confirm. If it is just pure gensim word2vec SG then this will be fine for me to port the walks to the second tool.

Thank you!

**Comment by eliorc** [comment]
1. True
2. Not altered at all

**Comment by amjass12** [comment]
Great! Thank you for clarifying!
