### ISSUE TITLE
Feature Request: Option to disable progress bar

### ISSUE THREAD

**Issue by JSybrandt** [eliorc/node2vec#7]
I'm using Node2Vec in another lib and I don't necessarily want to see the progress bar when I'm running tests or encapsulating functions.

**Comment by eliorc** [comment]
That's a good use case, I'll add a `quiet` flag option to the Node2vec constructor when I'll have time and update here

**Comment by eliorc** [comment]
I've added a `quiet` flag on the constructor of `Node2Vec` (version 0.1.3)
