### ISSUE TITLE
edge weight

### ISSUE THREAD

**Issue by suhanjiang** [eliorc/node2vec#71]
I cannot understand the weight_key in the code.
I was wondering how to deal with the situation where each edge has a weight to represent distance between two nodes.
Do I just generate a weighted graph using networkx?

**Comment by eliorc** [comment]
You can see in the official docs of networkx, [how to add weights to edges](https://networkx.org/documentation/stable/auto_examples/drawing/plot_weighted_graph.html).
The `weight_key` is the key used to specify the weight, as you can see in the docs, they use `weight` as the key name - and that is the default value of `weight_key`. Basically `weight_key` is the key name of where you keep your weights.

**Comment by suhanjiang** [comment]
Thanks for your reply. Thus, this code is a weighted node2vec version?

**Comment by suhanjiang** [comment]
BTW, the weight means the probability of random walking or just represents a feature (like the distance between the connected nodes) of the graph?

**Comment by eliorc** [comment]
Yes, if you use weights the probabilities will distribute by the weights assigned. So if you have a weight of 2 and a weight of 1, it will be twice as probable to travel to 2 than to 1.

**Comment by suhanjiang** [comment]
thx for your help!!!
