### ISSUE TITLE
Parameters tuning for word2vec

### ISSUE THREAD

**Issue by hhu1** [eliorc/node2vec#72]
Hi, I'm wondering if I should be spending time tuning the following parameters: window, min_count, batch_words.

I understand all other parameters but have little intuition over these parameters. Do they only affect computational time? Or do they have meaningful impact over node2vec embedding values as well? Could you offer any advice /intuition about how to tune these parameters?

Appreciate your suggestions.

**Comment by eliorc** [comment]
`window` is the most significant from the three, then `min_count` and `batch_words` is last. Since these are `gensims`'s variables for optimization you should read in `gensim.Word2Vec` docs about this - assuming you are familiar with the `Word2Vec` algorithm
