### ISSUE TITLE
Associating embeddings with input nodes

### ISSUE THREAD

**Issue by horvathr** [eliorc/node2vec#73]
Is it possible to identify which node an embedding represents?

Thank you

**Comment by eliorc** [comment]
Yes, this should be rather obvious. How do you access the embeddings if not by their node identifier?

**Comment by horvathr** [comment]
I apologize for my ignorance since I’m just a beginner to node2vec.
However, I would like to re-phrase my question.

My requirement is such that I need to identify the node id for each row of
embeddings returned in the model by node2vec.fit. How can I associate each
row of embeddings with a node id from network graph.


Thank you

**Comment by eliorc** [comment]
The returned object from `fit` is a `gensim.models.word2vec.Word2Vec` - so the question is "how to get the id for each row in gensim word2vec" is what you should google.

Example code:

```python3
import networkx as nx
from node2vec import Node2Vec

# Create a graph
graph = nx.fast_gnp_random_graph(n=100, p=0.5)

# Precompute probabilities and generate walks - **ON WINDOWS ONLY WORKS WITH workers=1**
node2vec = Node2Vec(graph, dimensions=64, walk_length=30, num_walks=200, workers=4)  # Use temp_folder for big graphs

# Embed nodes
model = node2vec.fit(window=10, min_count=1, batch_words=4)  # Any keywords acceptable by gensim.Word2Vec can be passed, `dimensions` and `workers` are automatically passed (from the Node2Vec constructor)
```

After you run this, in `model.wv.vectors` you can access a matrix where each row is an embedding. The mapping between a node name and the index in that matrix can be found in `model.wv.index_to_key`

**Comment by horvathr** [comment]
Thank you very much. You have been very helpful.
