### ISSUE TITLE
Optimzation of embeddings

### ISSUE THREAD

**Issue by nawabhussain** [eliorc/node2vec#74]
I am trying to generate embeddings for a graph that is mostly influenced by Wikidata.  The optimization aims to increase the similarity of local networks more than ones that are not directly connected to a node.  In the attached sample graph, if B is the reference node, I want to maximise its similarity with the nodes A, C, D, and lower with node E. I have tried a few combinations for the parameters, but I would appreciate your insight as well. 

Should I focus on optimizing the values of p and q or are there any other parameters that could affect such similarities? 
![sample_graph](https://user-images.githubusercontent.com/18714720/127154634-d637170b-4f49-47c3-be1d-b75c8daf4e58.png)

**Comment by eliorc** [comment]
From the article itself

> **Return parameter, p.** Parameter p controls the likelihood of immediately revisiting a node in the walk. Setting it to a high value
> (> max(q, 1)) ensures that we are less likely to sample an alreadyvisited node in the following two steps (unless the next node in
> the walk had no other neighbor). This strategy encourages moderate exploration and avoids 2-hop redundancy in sampling. On the
> other hand, if p is low (< min(q, 1)), it would lead the walk to
> backtrack a step (Figure 2) and this would keep the walk “local”
> close to the starting node u.
> 
> **In-out parameter, q.** Parameter q allows the search to differentiate
> between “inward” and “outward” nodes. Going back to Figure 2,
> if q > 1, the random walk is biased towards nodes close to node t.
> Such walks obtain a local view of the underlying graph with respect
> to the start node in the walk and approximate BFS behavior in the
> sense that our samples comprise of nodes within a small locality.
> In contrast, if q < 1, the walk is more inclined to visit nodes
> which are further away from the node t. Such behavior is reflective of DFS which encourages outward exploration. However, an
> essential difference here is that we achieve DFS-like exploration
> within the random walk framework. Hence, the sampled nodes are
> not at strictly increasing distances from a given source node u, but
> in turn, we benefit from tractable preprocessing and superior sampling efficiency of random walks. Note that by setting πv,x to be
> a function of the preceeding node in the walk t, the random walks
> are 2nd order Markovian.
