### ISSUE TITLE
How to pass my own walks?

### ISSUE THREAD

**Issue by oleg-kachan** [eliorc/node2vec#75]
Are there possibility to pass my own set of walks (and not to rely on built-in sampler) on a graph to the part of the code computing embedding?

**Comment by nawabhussain** [comment]
Have you tried modifying the walks parameter of the Node2vec object?

**Comment by eliorc** [comment]
If you want to pass your own walks, no need for the node2vec package - simply use `gensim.Word2Vec`

**Comment by oleg-kachan** [comment]
yeah, still it would be nice if one could implement custom biased random walk sampler within node2vec package
