### ISSUE TITLE
Suggestions for running this on large graphs

### ISSUE THREAD

**Issue by KarthikRevanuru** [eliorc/node2vec#77]
@eliorc is this optimised for large graphs ? 
1) I've a graph with 4.5M nodes and 80M edges. What is your rough estimate of running time on large graphs like this.
2) How does temp dir help ?
3) Does it use networkx for large graphs or do you use anything better like CSR matrix ?

**Comment by eliorc** [comment]
I can not give a time eatimate, but in general it ia not optimised for very large graphs as you specified.

The temp dir helps with handling the memory part of large graphs, not the speed part
