### ISSUE TITLE
defining random state or seed option parameters.

### ISSUE THREAD

**Issue by kahramankostas** [eliorc/node2vec#79]
I need the option to assign random state or seed values to get stable results. I don't think there is such an option.
Unfortunately, my attempts to fix the general seed that I have listed below did not solve the problem.

```python
import random
random.seed(1)
from numpy.random import seed
seed(1)
```

What can be done about it? Do you have any advice?
thanks in advance

**Comment by eliorc** [comment]
There is an option and it is documented in the main README, look for the word "seed"

In any case, in the current implementation, it only works when using a single worker
