### ISSUE TITLE
Maximum recursion depth exceed

### ISSUE THREAD

**Issue by shrimonmuke0202** [eliorc/node2vec#80]
RecursionError: maximum recursion depth exceeded while calling a Python object. This type of error is shown when I am running node2vec for 64000 graphs. How can I get rid of this problem?

**Comment by eliorc** [comment]
Can you put the full stack trace?

**Comment by shrimonmuke0202** [comment]
Traceback (most recent call last):
  File "training.py", line 117, in <module>
    train_data_list,y_train = Pyg_data_preparation("Train.csv")
  File "training.py", line 108, in Pyg_data_preparation
    x = featurecreation_node2vec(path)
  File "training.py", line 52, in featurecreation_node2vec
    node2vec = Node2Vec(graph=graph,dimensions=128,walk_length=16,num_walks=100,workers=5)
  File "/home/csu/.local/lib/python3.8/site-packages/node2vec/node2vec.py", line 73, in __init__
    self._precompute_probabilities()
  File "/home/csu/.local/lib/python3.8/site-packages/node2vec/node2vec.py", line 84, in _precompute_probabilities
    else tqdm(self.graph.nodes(), desc='Computing transition probabilities')
  File "/home/csu/.local/lib/python3.8/site-packages/tqdm/asyncio.py", line 23, in __init__
    super(tqdm_asyncio, self).__init__(iterable, *args, **kwargs)
  File "/usr/lib/python3.8/functools.py", line 399, in _method
    return self.func(cls_or_self, *self.args, *args, **keywords)
  File "/usr/lib/python3.8/functools.py", line 399, in _method
    return self.func(cls_or_self, *self.args, *args, **keywords)
  File "/usr/lib/python3.8/functools.py", line 399, in _method
    return self.func(cls_or_self, *self.args, *args, **keywords)
  [Previous line repeated 981 more times]
  File "/home/csu/.local/lib/python3.8/site-packages/tqdm/std.py", line 997, in __init__
    self._instances.remove(self)
  File "/usr/lib/python3.8/_weakrefset.py", line 109, in remove
    self.data.remove(ref(item))
  File "/home/csu/.local/lib/python3.8/site-packages/tqdm/utils.py", line 74, in __eq__
    return self._comparable == other._comparable
  File "/home/csu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1152, in _comparable
    return abs(getattr(self, "pos", 1 << 31))
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by eliorc** [comment]
Can you try executing again, but his time pass `quiet=True` to the constructor?

**Comment by vorakunal** [comment]
import sys
sys.setrecursionlimit(10000)

try this, it might work.

**Comment by vorakunal** [comment]
> Traceback (most recent call last): File "training.py", line 117, in train_data_list,y_train = Pyg_data_preparation("Train.csv") File "training.py", line 108, in Pyg_data_preparation x = featurecreation_node2vec(path) File "training.py", line 52, in featurecreation_node2vec node2vec = Node2Vec(graph=graph,dimensions=128,walk_length=16,num_walks=100,workers=5) File "/home/csu/.local/lib/python3.8/site-packages/node2vec/node2vec.py", line 73, in **init** self._precompute_probabilities() File "/home/csu/.local/lib/python3.8/site-packages/node2vec/node2vec.py", line 84, in _precompute_probabilities else tqdm(self.graph.nodes(), desc='Computing transition probabilities') File "/home/csu/.local/lib/python3.8/site-packages/tqdm/asyncio.py", line 23, in **init** super(tqdm_asyncio, self).**init**(iterable, *args, **kwargs) File "/usr/lib/python3.8/functools.py", line 399, in _method return self.func(cls_or_self, *self.args, *args, **keywords) File "/usr/lib/python3.8/functools.py", line 399, in _method return self.func(cls_or_self, *self.args, *args, **keywords) File "/usr/lib/python3.8/functools.py", line 399, in _method return self.func(cls_or_self, *self.args, *args, **keywords) [Previous line repeated 981 more times] File "/home/csu/.local/lib/python3.8/site-packages/tqdm/std.py", line 997, in **init** self._instances.remove(self) File "/usr/lib/python3.8/_weakrefset.py", line 109, in remove self.data.remove(ref(item)) File "/home/csu/.local/lib/python3.8/site-packages/tqdm/utils.py", line 74, in **eq** return self._comparable == other._comparable File "/home/csu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1152, in _comparable return abs(getattr(self, "pos", 1 << 31)) RecursionError: maximum recursion depth exceeded while calling a Python object

import sys
sys.setrecursionlimit(10000)

try this, it might work.

**Comment by vorakunal** [comment]
> Traceback (most recent call last): File "training.py", line 117, in train_data_list,y_train = Pyg_data_preparation("Train.csv") File "training.py", line 108, in Pyg_data_preparation x = featurecreation_node2vec(path) File "training.py", line 52, in featurecreation_node2vec node2vec = Node2Vec(graph=graph,dimensions=128,walk_length=16,num_walks=100,workers=5) File "/home/csu/.local/lib/python3.8/site-packages/node2vec/node2vec.py", line 73, in **init** self._precompute_probabilities() File "/home/csu/.local/lib/python3.8/site-packages/node2vec/node2vec.py", line 84, in _precompute_probabilities else tqdm(self.graph.nodes(), desc='Computing transition probabilities') File "/home/csu/.local/lib/python3.8/site-packages/tqdm/asyncio.py", line 23, in **init** super(tqdm_asyncio, self).**init**(iterable, *args, **kwargs) File "/usr/lib/python3.8/functools.py", line 399, in _method return self.func(cls_or_self, *self.args, *args, **keywords) File "/usr/lib/python3.8/functools.py", line 399, in _method return self.func(cls_or_self, *self.args, *args, **keywords) File "/usr/lib/python3.8/functools.py", line 399, in _method return self.func(cls_or_self, *self.args, *args, **keywords) [Previous line repeated 981 more times] File "/home/csu/.local/lib/python3.8/site-packages/tqdm/std.py", line 997, in **init** self._instances.remove(self) File "/usr/lib/python3.8/_weakrefset.py", line 109, in remove self.data.remove(ref(item)) File "/home/csu/.local/lib/python3.8/site-packages/tqdm/utils.py", line 74, in **eq** return self._comparable == other._comparable File "/home/csu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1152, in _comparable return abs(getattr(self, "pos", 1 << 31)) RecursionError: maximum recursion depth exceeded while calling a Python object

import sys
sys.setrecursionlimit(100000)

try this, it might work.
