### ISSUE TITLE
Can we use any technique other than word2vec in the implementation of node2vec for finding embeddings?

### ISSUE THREAD

**Issue by Sanchita333** [eliorc/node2vec#81]
Can we use any technique other than word2vec like Glove ,TF-IDF, Fast-Text etc. in the implementation of node2vec for finding embeddings.

**Comment by eliorc** [comment]
I don't have support for this, but absolutely can be done, you can use whatever algo you wish on the generated walks, but it will no longer be the node2vec algorithm
