### ISSUE TITLE
Clarification on node2vec on graph type

### ISSUE THREAD

**Issue by amjass12** [eliorc/node2vec#82]
Hi, 

I have been using your implementation of node2vec which works perfectly - firstly thank you very much for this easy to use tool. 

I have a question for clarification though - and surprisingly i could not find it in the original paper and with google searches!

The graphs I build contain nodes that are not all connected to each other - there may be communities of 5 nodes only, 10 nodes only, 300 nodes only etc... this is simply the nature of the graphs I am building as they are based on similarity metrics for the feature the nodes represent. Can I clarify that it is **STILL VALID** to run node2vec on a graph like this? I have a attached. a screenshot of what i mean - as you can see not all nodes are connected to each other - the embedding vectors and `.most_similar` cosines make sense after running walks and model fit but want to clarify this ok for the node2vec use case... 

I suspect this is totally fine as it simply means in the vocabulary, the disconnected components are always found together and never with the other nodes so that would just be reflected in the embedding vector and then cosine similarities?

thank you!
<img width="780" alt="Screenshot 2021-12-17 at 23 28 26" src="https://user-images.githubusercontent.com/33659783/146619076-0cb91b38-22ff-44f9-8646-bcd71a1d03ca.png">

**Comment by eliorc** [comment]
I don't see a reason why this wouldn't be valid in node2vec, seems perfectly file to me

**Comment by amjass12** [comment]
great thank you - i appreciate the feedback, I wasn't sure on the part with isolated communities - I do not see many examples (and indeed in the original paper) on graphs with lots of subgraphs . thank you for confirming!
