### ISSUE TITLE
batch_words argumewnt in .fit method

### ISSUE THREAD

**Issue by amjass12** [eliorc/node2vec#84]
Hi, 

Not an issue but a question for clarification - 

The batch_words example given in your vignette in the main github page used `batch_word=4` as a gensim.Word2Vec parameter in the `.fit method`

The Word2Vec default parameters are set to `10000` - https://radimrehurek.com/gensim/models/word2vec.html

I was wondering why, you chose 4 specifically in your toy example - and what effect  changing this parameter will have on training, my understanding is that this is simply the number of target-context pairs that are passed to processors at a time?

Leaving this as default to 10,000 should not affect training correct?

thank you!

**Comment by eliorc** [comment]
I had no data science reason to do so, I just wanted the documentation to reflect how you can inject hyperparameters to the Word2Vec part of the algorithm

**Comment by amjass12** [comment]
great - thank you!  will continue with default w2v hyperparameters
