### ISSUE TITLE
[Question] about directed graph and weight

### ISSUE THREAD

**Issue by JulianaGuama** [eliorc/node2vec#85]
I have some questions:
- Have you tested the results with the ones shown in the paper?
- Have you made some fixing in the framework for the algoritm work with directed graphs?¹

¹ I'm asking this because for what I read in the paper section 3 there is an assumption of `Symmetry in feature space. A source node and neighborhood node have a symmetric effect over each other in feature space`, witch I understood as that this framework if for undirected graphs only. But, the gihub that the project suggest (that use Python 2.7) also allow the use of directed graphs. Finally, I saw issue #36 where I understood that it was need a fixing to proprely work with directed graphs.

**Comment by eliorc** [comment]
1) No
2) Yes, previously there was a bug with directed Graphs that was fixed in [0.3.3](https://github.com/eliorc/node2vec/releases/tag/v0.3.3)
