### ISSUE TITLE
Interpretation of weights

### ISSUE THREAD

**Issue by MOOOOOSER** [eliorc/node2vec#87]
I struggle with comprehending, how weights are interpreted in the algorithm. Is the weight interpreted as a distance or opposite (similarity score)? Thanks in advance.

**Comment by eliorc** [comment]
In Node2vec weights are used for calculating the transition probabilities between one node and another during the random walks.
The higher a weight is for one walk-candidate relatively to the other walk-candidates, the more probability the next step in the walk will be to that node.

**Comment by MOOOOOSER** [comment]
Thank you very much for the explanation.
