### ISSUE TITLE
can same temp directory be used for different graphs in for loop training?

### ISSUE THREAD

**Issue by amjass12** [eliorc/node2vec#93]
Hi, 

I have several large graphs that I am looping over to train and I am using the temp directory parameter as they are large graphs and I run in to a memory error without it. So far, with the temp directoy paramater it works fine. However, is it ok to use the **same** temp directory for every unique graph? this should not interfere with training or carry any information from the previous graph right? my code is below 
```
files = [f for f in os.listdir('graphdir/') if any(f.endswith(ext) for ext in '.gpickle')]
save_names = [re.sub('.gpickle', '', i) for i in files]

for i, j in zip(files, save_names):
    print(f'reading in {i} for save name {j}')
    graph_network = nx.read_gpickle(os.path.join('graphdir/', i))
    graph_walk = Node2Vec(graph_network, dimensions=100, walk_length=80, num_walks=400, p=1.0, q=0.7, workers=38, temp_folder='temp_directory/')
    model = graph_walk.fit(window=10, epochs=25)

    model.save(f'slown2v_word2vec_SG_window10_for_{j}.model')
```
as you can see, for every iteration, when it goes to the next graph for training, it simply will use the same temp directory. is this ok?, there won;t be any information leakage from the previous training right? either by the loop itself or by the temp directory?

thank you!

**Comment by eliorc** [comment]
No, they won't interfere one with another, as long as you run them sequentially (like you do here in a `for` loop)

**Comment by amjass12** [comment]
Hi @eliorc 

thank you very much for this - I am running this on many graphs, so the for loop makes sense, thank you for clarifying its use is fine - just to follow up with 2 final questions:

1. I am not sure exactly what the temp_dir is doing (I have looked at the source and it isn't clear to me) can you clarify how it assists in large graph training - is it memory allocation?

2. As you confirmed the for loop is fine, there should also be no issue with previous walk and model data in the loop itself right? i.e. when iterating to next walk.. the `graph_walk` variable is completely overwritten with the **new** iteration and also same for model and absolutely no information from previous walks/model initialisation is saved correct? - in other words it is fresh each time? Only reason i want to clarify is to be sure that NO weights from the previous model in one iteration are carried over to the next model (again, you have clarified but just want to be concrete), although each model vocabulary size and `.most_similar` suggests they are fine and all unique. 

thank you!

**Comment by eliorc** [comment]
about 1. you can read [here](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html#:~:text=in%20that%20case.-,temp_folder,-%3A%20str%2C%20optional)

about 2., no problem, everytime you reinitialize `Node2Vec` you start from scratch

**Comment by amjass12** [comment]
thank you so much!
