### ISSUE TITLE
_precompute_probabilities parallel execution

### ISSUE THREAD

**Issue by bl3e967** [eliorc/node2vec#94]
Hi, 

I have a v. large graph at the moment where it is taking a while on the precomputation stage. I see that the parallel execution for the probability precomputation is added as a ToDo - is there a timeline set for this implementation? 

Many thanks in advance!

**Comment by eliorc** [comment]
Nope, I'm not working on this project currently, I would love to accept a PR though :)

**Comment by bl3e967** [comment]
Good to know, thanks for the response. Can't promise anything but will take a look at it as I am actively using the repo for my work. Thanks!
