### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by HangXue-lab** [eliorc/node2vec#96]
trying to run the code provided locally, but the program gives the error warning: 
`ImportError: cannot import name 'metadata' from importlib`.
The error results from code segment "from importlib import metadata", which is from ./node2vec/node2vec/__init__.py.

How to solve the problem?

**Comment by eliorc** [comment]
Which Python version are you running?

**Comment by HangXue-lab** [comment]
Python3.7.3，so how should I do next



---- Replied Message ----
| From | Elior ***@***.***> |
| Date | 10/27/2022 14:03 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [eliorc/node2vec] import error (Issue #96) |

Which Python version are you running?

**Comment by eliorc** [comment]
Can you please provide the full stack trace?
