### ISSUE TITLE
segmentation fault 

### ISSUE THREAD

**Issue by willleeney** [eliorc/node2vec#97]
getting this error: 

```
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Segmentation fault: 11
```
 followed by:
```

UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by eliorc** [comment]
This is a Python standard error that appears when you are out of RAM.
If your graph is very big, try using `temp_folder` in the constructor's argument

**Comment by willleeney** [comment]
unfortunately i am already using the temp folder option. Is there some rough estimate in terms of size of nx.graph to minimum available ram needed?

**Comment by willleeney** [comment]
this was on cora?

**Comment by eliorc** [comment]
What does that mean?
