### ISSUE TITLE
How to set parameters for a collection small disconnected graphs

### ISSUE THREAD

**Issue by MikeB2019x** [eliorc/node2vec#99]
I have a collection of 1000 small graphs each 2 to 10 nodes each.  The graphs are all independent ie. they are not connected to each other.  I decided to use node2vec to allow comparison of the graphs.  My thinking was that I could do PCA on the embeddings to identify similar graphs.  It works but I have a concern.

Working in Python and using node2vec, I get the nicest results graphically with setting only the following parameters (all others are set to default):
```  
dimensions=16, walk_length=30, num_walks=100, workers=4
```
What concerns me are walk length/random walk.   While I get a result it's not clear to me it makes any sense ie. no better than random luck.  For example, why would a walk_length of 30 be meaningful when the graphs are so small?  Will the algorithm actually end up 'jumping' to a node in another graph?

As I said, I can tune the parameters to get a result and I have read several papers/articles but none seems to answer my question/situation.  Does what I'm doing make any sense and it is just luck that _mostly_ similar graphs seem to cluster?  Any assistance is appreciated and if the answer is obvious just indicate what I should be reading/looking at.   

TIA

**Comment by eliorc** [comment]
It's hard to say, but I'll try my best to explain the parameters' impact on your result.
Essentially you decide how you want to embed information from your graph into the embedding space using the different hyperparameters.
I'd say `num_walk` is mostly for robustness, if your graphs are small enough I don't think you will gain from greater `num_walk` - this only defines the number of walks you will created from each node. In turn, these random walks are the input data for a skip-gram algorithm (just like Word2Vec). So you are just creating more data.

Walk length, jointly with `window_size` (which if you don't set, is set to 5 by `gensim`), `q` and `p` define how these walks are constructed. It will be too much for me to explain here, but if you want to understand this better I'd suggest to

1. Learn about the Word2Vec algorithm, and the role of window size in the algorithm
2. Learn about `q` and `p` (you can do so from looking at my PyData video in the README)

I think this will give you enough context to understand what you are looking for

**Comment by MikeB2019x** [comment]
@eliorc Thank you for the reply.   I had done all that you describe and read several papers before asking the question.  However, everything I've read seems to assume one large mostly connected graph esp. a social network or citations.  I see my case as substantively different.  I'll keep looking.  Thanks again for your time.
